version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 50m

  backend:
    build: .
    command: > 
        bash -c "python /code/wait_for_postgres.py && /code/manage.py migrate && /code/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    logging:
      options:
        max-size: 50m

volumes:
    postgres:

