# Generated by Django 2.2 on 2019-04-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('coin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[('S', 'Stake'), ('C', 'Coin'), ('D', 'Data')], default=1)),
                ('sender', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlockHeader',
            fields=[
                ('version', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('block_number', models.IntegerField()),
                ('validator', models.CharField(default='XXXXXXXXXXXXXX', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('block_reward', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('block_hash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('parent_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_hash', to='mock.BlockHeader')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='mock.BlockHeader')),
                ('transactions', models.ManyToManyField(related_name='blocks', to='mock.Transaction')),
            ],
        ),
    ]
